# Site settings
title: Battalion Theatre
email: battaliontheatre@gmail.com
url:  http://dorothythurston.github.io/battalion
baseurl: ""
description: "A New York based theatre company dedicated to following the fun to the truth of the human condition and then putting it in front of an audience."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Battalion Theatre

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BattalionThtr
  - title: facebook
    url: https://facebook.com/BattalionTheatre
  - title: instagram
    url: https://instagram.com/BattalionTheatre

# Build settings
markdown: kramdown
permalink: pretty
